apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: telegraf
    user: admin
    password: Welcome1234
    url: http://influxdb:8086
    isDefault: true
    editable: true